// <auto-generated />
using System;
using GoToWorkDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoToWorkDatabase.Migrations
{
    [DbContext(typeof(GoToWorkDbContext))]
    partial class GoToWorkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoToWorkDatabase.Models.Detail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Material")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.DetailProduct", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.Property<string>("DetailId")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "DetailId");

                    b.HasIndex("DetailId");

                    b.ToTable("DetailProducts");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.DetailProduction", b =>
                {
                    b.Property<string>("ProductionId")
                        .HasColumnType("text");

                    b.Property<string>("DetailId")
                        .HasColumnType("text");

                    b.HasKey("ProductionId", "DetailId");

                    b.HasIndex("DetailId");

                    b.ToTable("DetailProductions");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfDelete")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.EmployeeMachine", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<string>("MachineId")
                        .HasColumnType("text");

                    b.HasKey("EmployeeId", "MachineId");

                    b.HasIndex("MachineId");

                    b.ToTable("EmployeeMachines");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.EmployeeWorkshop", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<string>("WorkshopId")
                        .HasColumnType("text");

                    b.HasKey("EmployeeId", "WorkshopId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("EmployeeWorkshops");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Machine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<int>("MachineType")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.MachineProduct", b =>
                {
                    b.Property<string>("MachineId")
                        .HasColumnType("text");

                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.HasKey("MachineId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("MachineProducts");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Production", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("WorkshopId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Productions");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.ProductionWorkshop", b =>
                {
                    b.Property<string>("ProductionId")
                        .HasColumnType("text");

                    b.Property<string>("WorkshopId")
                        .HasColumnType("text");

                    b.HasKey("ProductionId", "WorkshopId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("ProductionWorkshops");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Workshop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Detail", b =>
                {
                    b.HasOne("GoToWorkDatabase.Models.User", "User")
                        .WithMany("Details")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.DetailProduct", b =>
                {
                    b.HasOne("GoToWorkDatabase.Models.Detail", "Detail")
                        .WithMany("Products")
                        .HasForeignKey("DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoToWorkDatabase.Models.Product", "Product")
                        .WithMany("Details")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detail");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.DetailProduction", b =>
                {
                    b.HasOne("GoToWorkDatabase.Models.Detail", "Detail")
                        .WithMany("Productions")
                        .HasForeignKey("DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoToWorkDatabase.Models.Production", "Production")
                        .WithMany("Details")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detail");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Employee", b =>
                {
                    b.HasOne("GoToWorkDatabase.Models.User", "User")
                        .WithMany("Employees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.EmployeeMachine", b =>
                {
                    b.HasOne("GoToWorkDatabase.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoToWorkDatabase.Models.Machine", "Machine")
                        .WithMany("Employees")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.EmployeeWorkshop", b =>
                {
                    b.HasOne("GoToWorkDatabase.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoToWorkDatabase.Models.Workshop", "Workshop")
                        .WithMany("EmployeeWorkshops")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Machine", b =>
                {
                    b.HasOne("GoToWorkDatabase.Models.Employee", null)
                        .WithMany("Machines")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.MachineProduct", b =>
                {
                    b.HasOne("GoToWorkDatabase.Models.Machine", "Machine")
                        .WithMany("Products")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoToWorkDatabase.Models.Product", "Product")
                        .WithMany("Products")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Product", b =>
                {
                    b.HasOne("GoToWorkDatabase.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Production", b =>
                {
                    b.HasOne("GoToWorkDatabase.Models.Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.ProductionWorkshop", b =>
                {
                    b.HasOne("GoToWorkDatabase.Models.Production", "Production")
                        .WithMany()
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoToWorkDatabase.Models.Workshop", "Workshop")
                        .WithMany()
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Production");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Workshop", b =>
                {
                    b.HasOne("GoToWorkDatabase.Models.Employee", null)
                        .WithMany("Workshops")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Detail", b =>
                {
                    b.Navigation("Productions");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Employee", b =>
                {
                    b.Navigation("Machines");

                    b.Navigation("Workshops");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Machine", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Product", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Production", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.User", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("GoToWorkDatabase.Models.Workshop", b =>
                {
                    b.Navigation("EmployeeWorkshops");
                });
#pragma warning restore 612, 618
        }
    }
}
